// Glen Rejeki Sitorus
// 11S23024
// Informatika
#include <stdio.h>

#define PI 3.14159

int main () {
  double r ;
  scanf ("%lf",&r);

  double luas = r * r * PI;
  printf ("%lf",luas);
  return 0;
}

// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu
// Komen bosmu